import java.util.Properties
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    // AGP 9+ ships Kotlin support built in — the separate
    // `org.jetbrains.kotlin.android` plugin is not just unnecessary, it is a
    // hard error to apply alongside it (see
    // https://issuetracker.google.com/438678642). The serialization and
    // Compose compiler plugins are still separate and still required.
    id("com.android.application")
    id("org.jetbrains.kotlin.plugin.serialization")
    id("org.jetbrains.kotlin.plugin.compose")
    id("org.openapi.generator")
}

// `local.properties` is per-machine and gitignored (see local.properties.example
// at the module root). It never carries a real secret for this feature — just
// the API base URL — but the mechanism is the same one credentials would use.
val localProperties = Properties().apply {
    val file = rootProject.file("local.properties")
    if (file.exists()) file.inputStream().use { load(it) }
}

// The OpenAPI document checked in at apps/api/openapi.json is generated by
// B7 (`npm run generate:openapi -w apps/api`) from the Zod schemas in
// packages/contracts. It is the single source of truth for every request/
// response model this app uses — nothing here hand-writes a duplicate shape.
val openApiSpec = rootProject.projectDir.parentFile.parentFile
    .resolve("apps/api/openapi.json")
val generatedApiPackage = "com.folusayo.kobolink.generated.api"
val generatedSourcesDir = layout.buildDirectory.dir("generated/openapi")
val normalizedSpec = layout.buildDirectory.file("openapi/openapi.normalized.json")

// --- Spec normalisation (OpenAPI 3.1 -> 3.0-shaped) before generation ---
//
// The document is OpenAPI 3.1 as emitted from Zod. openapi-generator's 3.1
// support is beta and mis-generates the two constructs Zod's `.nullable()`
// and `z.literal()` produce:
//   - `anyOf: [T, {type: "null"}]` on a hoisted inline object becomes an
//     EMPTY wrapper class, so `counterparty: "Ada"` cannot decode (the
//     transfer response, the transaction list, and `phone` on login);
//   - `type: [T, "null"]` becomes a non-null `T` plus a bogus `HashMap`
//     supertype, so the last page's `nextCursor: null` cannot decode.
// Both are rewritten to the 3.0 spelling the generator handles (`T` +
// `nullable: true`); `const: X` becomes the one-value `enum: [X]` it already
// generated as. Nothing in apps/api/openapi.json or packages/contracts is
// edited: this only reshapes a copy under build/. Pinned by
// WalletPayloadDecodeTest and AuthPayloadDecodeTest.
fun normalizeSchemaNode(node: Any?): Any? = when (node) {
    is Map<*, *> -> {
        val out = LinkedHashMap<String, Any?>()
        node.forEach { (k, v) -> out[k as String] = normalizeSchemaNode(v) }
        val anyOf = out["anyOf"] as? List<*>
        if (anyOf != null && anyOf.size == 2) {
            val nullBranch = anyOf.singleOrNull { (it as? Map<*, *>)?.get("type") == "null" }
            if (nullBranch != null) {
                val other = anyOf.first { it !== nullBranch } as Map<*, *>
                out.remove("anyOf")
                other.forEach { (k, v) -> out.putIfAbsent(k as String, v) }
                out["nullable"] = true
            }
        }
        val type = out["type"]
        if (type is List<*> && type.size == 2 && type.contains("null")) {
            out["type"] = type.first { it != "null" }
            out["nullable"] = true
        }
        if (out.containsKey("const")) {
            // A one-value string enum is what 3.1 `const` generated as. A
            // numeric one (QrPayload.v) would generate an enum over
            // BigDecimal that does not compile, so it is just a number.
            val constant = out.remove("const")
            if (constant is String) out["enum"] = listOf(constant)
        }
        // 3.1-only keyword on `fields` maps (string keys); 3.0 rejects it.
        if (out["propertyNames"] is Map<*, *>) out.remove("propertyNames")
        out
    }
    is List<*> -> node.map { normalizeSchemaNode(it) }
    else -> node
}

val normalizeOpenApi = tasks.register("normalizeOpenApi") {
    inputs.file(openApiSpec)
    outputs.file(normalizedSpec)
    doLast {
        val root = groovy.json.JsonSlurper().parse(openApiSpec)
        @Suppress("UNCHECKED_CAST")
        val normalized = normalizeSchemaNode(root) as MutableMap<String, Any?>
        normalized["openapi"] = "3.0.3"
        val target = normalizedSpec.get().asFile
        target.parentFile.mkdirs()
        target.writeText(groovy.json.JsonOutput.toJson(normalized))
    }
}

android {
    namespace = "com.folusayo.kobolink"
    compileSdk = 37

    defaultConfig {
        applicationId = "com.folusayo.kobolink"
        minSdk = 26
        targetSdk = 37
        versionCode = 1
        versionName = "0.1.0"

        val apiBaseUrl = (localProperties.getProperty("kobolink.apiBaseUrl")
            ?: System.getenv("KOBOLINK_API_BASE_URL")
            ?: "http://10.0.2.2:3001/")
        buildConfigField("String", "API_BASE_URL", "\"$apiBaseUrl\"")

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlin {
        jvmToolchain(17)
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
            excludes += "/META-INF/DEPENDENCIES"
        }
    }

    sourceSets {
        getByName("main") {
            // A plain File, not a Provider: AGP 9's SourceSet API refuses a
            // Provider here (it can't tell generated vs. static sources
            // apart that way) — see the Variant API's addGeneratedSourceDirectory
            // for the "correct" modern replacement. Freshness is still
            // guaranteed because every KotlinCompile task explicitly
            // dependsOn("openApiGenerate") below, so this directory is never
            // stale when the compiler reads it.
            kotlin.srcDir(generatedSourcesDir.get().dir("src/main/kotlin").asFile)
        }
    }
}

// --- Kotlin model + API-interface generation from the OpenAPI document ---
//
// This is the mechanism the M0 acceptance bar depends on: a field renamed or
// retyped in packages/contracts flows through B7's `npm run generate:openapi`
// into apps/api/openapi.json, and the next Android build regenerates these
// Kotlin models from that file. If application code still references the old
// shape, the regenerated model no longer matches it and `compileDebugKotlin`
// fails — a compile error, not a silent runtime bug.
openApiGenerate {
    generatorName.set("kotlin")
    inputSpec.set(normalizedSpec.get().asFile.absolutePath)
    outputDir.set(generatedSourcesDir.map { it.asFile.absolutePath })
    packageName.set(generatedApiPackage)
    apiPackage.set("$generatedApiPackage.apis")
    modelPackage.set("$generatedApiPackage.models")
    invokerPackage.set("$generatedApiPackage.infrastructure")

    // Upstream's "kotlin" generator (jvm-retrofit2 + kotlinx_serialization)
    // imports `retrofit2.converter.kotlinx.serialization.asConverterFactory`,
    // but the real com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter
    // artifact has always lived at
    // `com.jakewharton.retrofit2.converter.kotlinx.serialization` — a stale
    // template import that fails to compile as-is. This one-file template
    // override (openapi-templates/infrastructure/ApiClient.kt.mustache — a
    // custom templateDir is looked up flat, by the template's name within
    // its own category, NOT by the "kotlin-client/libraries/jvm-retrofit2/"
    // path the same file lives at inside the generator's jar) is an exact copy
    // of the upstream template with only that import corrected; every other
    // template still comes from the generator itself.
    templateDir.set(rootProject.projectDir.resolve("openapi-templates").absolutePath)

    // Retrofit + OkHttp client, kotlinx.serialization for JSON — see the PR
    // description for why. We deliberately do NOT restrict which supporting
    // files get generated: the "jvm-retrofit2" template's Serializer.kt
    // references a fixed set of type adapters (BigDecimalAdapter,
    // OffsetDateTimeAdapter, etc.) regardless of whether this spec happens to
    // use those types, so trimming that list by hand is a trap. Everything
    // lands under build/generated/openapi (gitignored); only the
    // src/main/kotlin subtree below is wired into the app's source set, so
    // the incidental build.gradle/docs/gradlew the generator also emits are
    // harmless clutter, never compiled or committed.
    library.set("jvm-retrofit2")

    // The OpenAPI document types every kobo field as a bare `type: integer`
    // (packages/contracts bounds them at Number.MAX_SAFE_INTEGER, but the
    // JSON Schema carries no `format: int64`), which the generator maps to a
    // 32-bit Int. A wallet balance is a ledger SUM and can pass 2^31-1 kobo
    // (about 21.4 million naira); the generated Wallet model then fails to
    // decode (GeneratedMoneyWidthTest). Widen every integer to Long here
    // rather than hand-edit generated models. The right long-term fix is
    // `format: int64` in contracts, which this module does not own.
    typeMappings.set(mapOf("integer" to "kotlin.Long"))

    additionalProperties.set(
        mapOf(
            "library" to "jvm-retrofit2",
            "serializationLibrary" to "kotlinx_serialization",
            "useCoroutines" to "true",
            "omitGradleWrapper" to "true",
            "generateModelTests" to "false",
            "generateModelDocumentation" to "false",
            "generateApiTests" to "false",
            "generateApiDocumentation" to "false",
        )
    )
}

// Wire the generator into the normal build graph: nobody has to remember to
// run `openApiGenerate` by hand, and a stale/missing spec fails the build
// rather than compiling against yesterday's models.
tasks.named("openApiGenerate") {
    dependsOn(normalizeOpenApi)
    // `inputSpec` above is a path string, so Gradle would not otherwise key
    // the task (or its build-cache entry) on the document's CONTENT: a spec
    // change could replay yesterday's generated models from the cache.
    inputs.file(normalizedSpec)
}
tasks.withType<KotlinCompile>().configureEach {
    dependsOn("openApiGenerate")
}
tasks.named("preBuild") {
    dependsOn("openApiGenerate")
}

dependencies {
    // -- Generated API client's own runtime deps --
    implementation("com.squareup.retrofit2:retrofit:2.12.0")
    implementation("com.squareup.retrofit2:converter-scalars:2.12.0")
    implementation("com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:1.0.0")
    implementation("com.squareup.okhttp3:okhttp:5.4.0")
    implementation("com.squareup.okhttp3:logging-interceptor:5.4.0")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.1")

    // -- Android + Compose (Material 3) --
    implementation("androidx.core:core-ktx:1.17.0")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.10.0")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.10.0")
    implementation("androidx.activity:activity-compose:1.11.0")
    implementation(platform("androidx.compose:compose-bom:2026.06.01"))
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-graphics")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material-icons-core")

    // -- M2: session storage --
    // EncryptedSharedPreferences (AES256-GCM values, AES256-SIV keys, backed
    // by a Keystore-resident MasterKey) is the only allowed home for the
    // mobile session token — PLAN.md's M2 done-when.
    implementation("androidx.security:security-crypto:1.1.0")

    debugImplementation("androidx.compose.ui:ui-tooling")

    testImplementation("junit:junit:4.13.2")
    testImplementation("com.squareup.okhttp3:mockwebserver:5.4.0")
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.10.1")

    androidTestImplementation(platform("androidx.compose:compose-bom:2026.06.01"))
    // Instrumented tests for EncryptedTokenStore: EncryptedSharedPreferences
    // needs a real Android Keystore, which only exists on a device/emulator,
    // not the JVM unit-test sandbox above.
    androidTestImplementation("androidx.test.ext:junit:1.3.0")
    androidTestImplementation("androidx.test:runner:1.7.0")
    androidTestImplementation("androidx.test:core:1.7.0")
}
