import java.util.Properties
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    // AGP 9+ ships Kotlin support built in — the separate
    // `org.jetbrains.kotlin.android` plugin is not just unnecessary, it is a
    // hard error to apply alongside it (see
    // https://issuetracker.google.com/438678642). The serialization and
    // Compose compiler plugins are still separate and still required.
    id("com.android.application")
    id("org.jetbrains.kotlin.plugin.serialization")
    id("org.jetbrains.kotlin.plugin.compose")
    id("org.openapi.generator")
}

// `local.properties` is per-machine and gitignored (see local.properties.example
// at the module root). It never carries a real secret for this feature — just
// the API base URL — but the mechanism is the same one credentials would use.
val localProperties = Properties().apply {
    val file = rootProject.file("local.properties")
    if (file.exists()) file.inputStream().use { load(it) }
}

// The OpenAPI document checked in at apps/api/openapi.json is generated by
// B7 (`npm run generate:openapi -w apps/api`) from the Zod schemas in
// packages/contracts. It is the single source of truth for every request/
// response model this app uses — nothing here hand-writes a duplicate shape.
val openApiSpec = rootProject.projectDir.parentFile.parentFile
    .resolve("apps/api/openapi.json")
val generatedApiPackage = "com.folusayo.kobolink.generated.api"
val generatedSourcesDir = layout.buildDirectory.dir("generated/openapi")

android {
    namespace = "com.folusayo.kobolink"
    compileSdk = 37

    defaultConfig {
        applicationId = "com.folusayo.kobolink"
        minSdk = 26
        targetSdk = 37
        versionCode = 1
        versionName = "0.1.0"

        val apiBaseUrl = (localProperties.getProperty("kobolink.apiBaseUrl")
            ?: System.getenv("KOBOLINK_API_BASE_URL")
            ?: "http://10.0.2.2:3001/")
        buildConfigField("String", "API_BASE_URL", "\"$apiBaseUrl\"")

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlin {
        jvmToolchain(17)
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
            excludes += "/META-INF/DEPENDENCIES"
        }
    }

    sourceSets {
        getByName("main") {
            // A plain File, not a Provider: AGP 9's SourceSet API refuses a
            // Provider here (it can't tell generated vs. static sources
            // apart that way) — see the Variant API's addGeneratedSourceDirectory
            // for the "correct" modern replacement. Freshness is still
            // guaranteed because every KotlinCompile task explicitly
            // dependsOn("openApiGenerate") below, so this directory is never
            // stale when the compiler reads it.
            kotlin.srcDir(generatedSourcesDir.get().dir("src/main/kotlin").asFile)
        }
    }
}

// --- Kotlin model + API-interface generation from the OpenAPI document ---
//
// This is the mechanism the M0 acceptance bar depends on: a field renamed or
// retyped in packages/contracts flows through B7's `npm run generate:openapi`
// into apps/api/openapi.json, and the next Android build regenerates these
// Kotlin models from that file. If application code still references the old
// shape, the regenerated model no longer matches it and `compileDebugKotlin`
// fails — a compile error, not a silent runtime bug.
openApiGenerate {
    generatorName.set("kotlin")
    inputSpec.set(openApiSpec.absolutePath)
    outputDir.set(generatedSourcesDir.map { it.asFile.absolutePath })
    packageName.set(generatedApiPackage)
    apiPackage.set("$generatedApiPackage.apis")
    modelPackage.set("$generatedApiPackage.models")
    invokerPackage.set("$generatedApiPackage.infrastructure")

    // Upstream's "kotlin" generator (jvm-retrofit2 + kotlinx_serialization)
    // imports `retrofit2.converter.kotlinx.serialization.asConverterFactory`,
    // but the real com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter
    // artifact has always lived at
    // `com.jakewharton.retrofit2.converter.kotlinx.serialization` — a stale
    // template import that fails to compile as-is. This one-file template
    // override (openapi-templates/infrastructure/ApiClient.kt.mustache — a
    // custom templateDir is looked up flat, by the template's name within
    // its own category, NOT by the "kotlin-client/libraries/jvm-retrofit2/"
    // path the same file lives at inside the generator's jar) is an exact copy
    // of the upstream template with only that import corrected; every other
    // template still comes from the generator itself.
    templateDir.set(rootProject.projectDir.resolve("openapi-templates").absolutePath)

    // Retrofit + OkHttp client, kotlinx.serialization for JSON — see the PR
    // description for why. We deliberately do NOT restrict which supporting
    // files get generated: the "jvm-retrofit2" template's Serializer.kt
    // references a fixed set of type adapters (BigDecimalAdapter,
    // OffsetDateTimeAdapter, etc.) regardless of whether this spec happens to
    // use those types, so trimming that list by hand is a trap. Everything
    // lands under build/generated/openapi (gitignored); only the
    // src/main/kotlin subtree below is wired into the app's source set, so
    // the incidental build.gradle/docs/gradlew the generator also emits are
    // harmless clutter, never compiled or committed.
    library.set("jvm-retrofit2")
    additionalProperties.set(
        mapOf(
            "library" to "jvm-retrofit2",
            "serializationLibrary" to "kotlinx_serialization",
            "useCoroutines" to "true",
            "omitGradleWrapper" to "true",
            "generateModelTests" to "false",
            "generateModelDocumentation" to "false",
            "generateApiTests" to "false",
            "generateApiDocumentation" to "false",
        )
    )
}

// Wire the generator into the normal build graph: nobody has to remember to
// run `openApiGenerate` by hand, and a stale/missing spec fails the build
// rather than compiling against yesterday's models.
tasks.withType<KotlinCompile>().configureEach {
    dependsOn("openApiGenerate")
}
tasks.named("preBuild") {
    dependsOn("openApiGenerate")
}

dependencies {
    // -- Generated API client's own runtime deps --
    implementation("com.squareup.retrofit2:retrofit:2.12.0")
    implementation("com.squareup.retrofit2:converter-scalars:2.12.0")
    implementation("com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:1.0.0")
    implementation("com.squareup.okhttp3:okhttp:5.4.0")
    implementation("com.squareup.okhttp3:logging-interceptor:5.4.0")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.1")

    // -- Android + Compose (Material 3) --
    implementation("androidx.core:core-ktx:1.17.0")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.10.0")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.10.0")
    implementation("androidx.activity:activity-compose:1.11.0")
    implementation(platform("androidx.compose:compose-bom:2026.06.01"))
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-graphics")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material-icons-core")

    debugImplementation("androidx.compose.ui:ui-tooling")

    testImplementation("junit:junit:4.13.2")
    androidTestImplementation(platform("androidx.compose:compose-bom:2026.06.01"))
}
